(ns df-front.features)

(def titles
  [:name,:xp,:requires,:description,:count,:source,:sticker])

(def features
  [["Acolyte","Background","","Once per game, during your turn: Exchange 2 COLORLESS for 1 GREEN.","2","Base",""  ],
   ["Criminal","Background","","Once per game, during your turn: Discard one card for 1 gold.","2","Base",""  ],
   ["Entertainer","Background","","Once per game, during your turn: Discard a card and you may permanently ignore a Requires X Play/Purchase/Class on one card.","2","Base",""  ],
   ["Folk Hero","Background","","Once per game, during your turn: Exchange 2 HP for 1 gold.","2","Base",""  ],
   ["Guild Artisan","Background","","Once per game, during your turn: Exchange 2 COLORLESS for 1 RED.","2","Base",""  ],
   ["Hermit","Background","","Once per game, during your turn: Exchange 1 gold to draw one card.","2","Base",""  ],
   ["Noble","Background","","Once per game, during your turn: Exchange 1 gold to for 1 HP.","2","Base",""  ],
   ["Outlander","Background","","Once per game, during your turn: Discard one card for 1 HP.","2","Base",""  ],
   ["Sage","Background","","Once per game, during your turn: Exchange 2 COLORLESS for 1 BLUE.","2","Base",""  ],
   ["Sailor","Background","","Once per game, during your turn: Exchange 2 HP to draw one card.","2","Base",""  ],
   ["Soldier","Background","","Once per game, during your turn: Exchange 2 COLORLESS for 1 BLACK.","2","Base",""  ],
   ["Street Urchin","Background","","Once per game, during your turn: Steal one gold from another player.","2","Base",""  ],
   ["On the Sly","10","","When you purchase a card, pay 1 less gold and put the card into your discard instead of your hand.","2","Base",""  ],
   ["Tough","10","","Continuous: Increase your starting HP by 1.","2","Base",""  ],
   ["Training","10","","Continuous: Increase your starting hand by 1.","2","Base",""  ],
   ["Tranquility","10","","When you are forced to discard one or more cards, draw a card after discarding.","2","Base",""  ],
   ["Wealthy","10","","Continuous: Increase your starting gold by 1.","2","Base",""  ],
   ["Denial","15","","Each time you would heal, gain 1 gold instead.","2","Base",""  ],
   ["Turn Undead","20","Cleric or Paladin Class","Once per Scene: All Undead encounters must Save. Failure: Those encounters must skip their next attack.","3","Base",""  ],
   ["Destroy Undead","75","Cleric Class","Once per Scene: All Undead encounters must Save. Failure: Those encounters must skip their next attack and take 1 level of damage","1","Base",""  ],
   ["Destroy Undead II","100","Cleric Class","Once per Scene: All Undead encounters must Save. Failure: Those encounters must skip their next attack and take 2 levels of damage","1","Base",""  ],
   ["Divine Intervention","100","Cleric Class","Once per game, during your turn: Shuffle your discard into your draw deck. Choose a number of cards to draw. If any of them are not Devotion cards, discard all the cards drawn this way.","1","Base",""  ],
   ["Life Domain","10","Cleric Class","Equipment Pack: You must remove one BLACK card and add one GREEN card.","1","Base",""  ],
   ["Disciple of Life","25","Cleric Class & Life Domain","When you heal a character, return one Grace card from your discard to your hand.","1","Base",""  ],
   ["Preserve Life","30","Cleric Class & Life Domain","Once per Scene, during your turn: Discard one Grace card to heal any character 1 HP.","1","Base",""  ],
   ["Divine Strike","50","Cleric Class & War Domain","During your turn, your first non-Basic card to deal damage deals +1 GREEN. (If a card deals damage to multiple targets, this only applies to one target.)","1","Base",""  ],
   ["Preserve Life II","50","Cleric Class & Life Domain","Once per Scene, during your turn: Discard one Grace card to heal any character 1 HP and yourself 1 HP.","1","Base",""  ],
   ["Supreme Healing","100","Cleric Class & Life Domain","When healing any character, make a Devotion Check. Success: Heal +1 HP.","1","Base",""  ],
   ["Eldritch Knight","20","Fighter Class","You also count as ARCANE Class. Equipment Pack: You must add one BLUE card and remove one BLACK card.","1","Base",""  ],
   ["Weapon Bond","20","Fighter Class & Eldritch Knight","During your turn, discard any one BLUE card to draw one card.","1","Base",""  ],
   ["War Magic","40","Fighter Class & Eldritch Knight","Every time you play a Cantrip card, deal +1 BLACK.","1","Base",""  ],
   ["Arcane Charge","50","Fighter Class & Eldritch Knight","Once per Scene, during your turn: Move all encounters facing one player to face you. If you discard any one BLUE card, each encounter deals -1 damage.","1","Base",""  ],
   ["Eldritch Strike","50","Fighter Class & Eldritch Knight","If you deal damage from two BLACK cards and one BLUE card against the same encounter, deal +BLUE, BLUE to the same encounter","1","Base",""  ],
   ["Improved War Magic","100","Fighter Class & Eldritch Knight","All BLUE cards gain SWORD ICON.","1","Base",""  ],
   ["Expertise","15","Deception Class","Before the game starts, purchase any RED card costing 2 or less.","2","Base",""  ],
   ["Expertise II","30","Deception Class","Before the game starts, purchase a RED card costing 2 or less and replace a Stealth card with it.","2","Base",""  ],
   ["Expertise III","60","Deception Class","Before the game starts, purchase any two RED cards, each costing 2 or less, and replace up to two Stealth cards with them.","1","Base",""  ],
   ["Expertise IV","100","Deception Class","Before the game starts, purchase up to three RED cards, each costing 2 or less, and replace up to three Stealth cards with them.","1","Base",""  ],
   ["Conjuration (Savant)","25","Wizard Class","All Conjuration cards cost -1. Equipment Pack: You must add one BLUE card and remove one card of any type.","2","Base",""  ],
   ["Minor Conjuration","10","Wizard Class & Conjuration (Savant)","Once per turn: Exchange 2 COLORLESS for BLACK or RED.","1","Base",""  ],
   ["Benign Transposition","30","Wizard Class & Conjuration (Savant)","Once per Scene, during your turn: Swap all encounters and Locations facing you with those of an adjacent player.","1","Base",""  ],
   ["Focused Conjuration","50","Wizard Class & Conjuration (Savant)","Once per Scene: After you play a Conjuration card, place it on top of your draw deck instead of in your discard.","1","Base",""  ],
   ["Focused Conjuration II","100","Wizard Class & Conjuration (Savant)","Once per Scene: After you play a Conjuration card, place it in your hand instead of in your discard.","1","Base",""  ],
   ["Evocation (Savant)","25","Wizard Class","All Evocation cards cost -1. Equipment Pack: You must add one BLUE card and remove one card of any type.","2","Base",""  ],
   ["Sculpt Spells","10","Wizard Class & Evocation (Savant)","Whenever an Evocation card deals damage to multiple encounters, it can also deal that multiple element to one additional encounter.","1","Base",""  ],
   ["Potent Cantrip","30","Wizard Class & Evocation (Savant)","If you play two Cantrips on the same encounter, deal + BLUE to the same encounter.","1","Base",""  ],
   ["Empower Evocation","50","Wizard Class & Evocation (Savant)","During your turn, discard any card to add twice its cost in colorless damage to any Evocation card's damage.","1","Base",""  ],
   ["Overchannel","100","Wizard Class & Evocation (Savant)","During your turn, add +2 COLORLESS to all non-Basic BLUE cards.","1","Base",""  ],
   ["Arcane Recovery","15","Arcane Class","During a Short Rest: Draw one card and discard one card.","2","Base",""  ],
   ["Arcane Recovery II","30","Arcane Class","During a Short Rest: Draw up to two cards. Then discard that number of cards.","2","Base",""  ],
   ["Arcane Recovery III","60","Arcane Class","During a Short Rest: Draw up to two cards. Then discard one card.","1","Base",""  ],
   ["Arcane Recovery IV","100","Arcane Class","During a Short Rest: Draw up to three cards. For each card drawn you must pay HP or discard one card.","1","Base",""  ],
   ["Magical Adept","10","Arcane Class","During your turn, discard one BLUE card to buy one BLUE card costing 5 or less from the Market and play it immediately.","2","Base",""  ],
   ["Warcaster","20","Arcane Class","Continuous: You may use any Armor. You may use any Shield except Deception; your Shield Magic Item Limitations is 1. Equipment Pack: You must remove one BLUE card and add one BLACK card.","2","Base",""  ],
   ["Spell Sniper","40","Arcane Class","Deal damage from Cantrip cards anywhere on the damage Track.","2","Base",""  ],
   ["Arcane Trickster","20","Rogue Class","You also count as ARCANE Class. Equipment Pack: You must add one BLUE card and remove one RED card.","2","Base",""  ],
   ["Ledgermain","20","Rogue Class & Arcane Trickster","Play BLUE and RED cards against Locations as Assists.","1","Base",""  ],
   ["Magical Ambush","40","Rogue Class & Arcane Trickster","During your turn, when dealing RED damage to an encounter not facing you, deal it +BLUE.","1","Base",""  ],
   ["Versatile Trickster","50","Rogue Class & Arcane Trickster","During your turn, if you play BLUE and RED cards, return a Basic card to your hand from your discard.","1","Base",""  ],
   ["Spell Thief","100","Rogue Class & Arcane Trickster","Once per Scene: Choose a BLUE encounter. This encounter must skip its next attack. The player deals its damage as colorless against another encounter.","1","Base",""  ],
   ["Thief","20","Rogue Class","Increase your starting gold by 1. Equipment Pack: You must add one RED card and remove one card of any type.","1","Base",""  ],
   ["Second-Storey Work","20","Rogue Class & Thief","During your turn, you may move normally or move after your Deal Damage phase.","1","Base",""  ],
   ["Supreme Sneak","30","Rogue Class & Thief","If you play no cards during your turn, you may return any Basic card from your discard to your hand.","1","Base",""  ],
   ["Fast Hands","40","Rogue Class & Thief","During your turn, make a Deception Check. Success: You may leave the card on top of your deck","1","Base",""  ],
   ["Use Magic Device","50","Rogue Class & Thief","At the start of the game: You ignore all Class restrictions on Magic Items. Your Magic Items deal +1 COLORLESS.","1","Base",""  ],
   ["Thief's Reflexes","100","Rogue Class & Thief","When a non-token encounter is placed facing you (including during the Encounter phase), immediately return a card from your discard into your hand and you may immediately play this card on that encounter.","1","Base",""  ],
   ["Thieves' Cant","10","Rogue Class","During your turn, any other player with Thieves' Cant may play one card as if it had Assist.","2","Base",""  ],
   ["Evasion","20","Rogue Class","During your turn, discard one card to have one encounter facing you deal -1 damage.","1","Base",""  ],
   ["Evasion II","50","Rogue Class","During your turn, discard two cards to have all encounters facing you deal -1 damage.","1","Base",""  ],
   ["Evasion III","100","Rogue Class","During your turn, discard two cards to have all encounters facing you deal -1 damage.","1","Base",""  ],
   ["Reliable Talent","50","Rogue Class","When you succeed on a Deception Check, pay 1 gold to draw the revealed card.","1","Base",""  ],
   ["Sneak Attack","10","Rogue Class","During your turn, discard a card to deal RED.","2","Base",""  ],
   ["Sneak Attack II","30","Rogue Class","During your turn, discard a card to deal your choice of BLACK, GREEN, RED, or BLUE.","1","Base",""  ],
   ["Sneak Attack III","60","Rogue Class","During your turn, discard a card to deal your choice of BLACK1, GREEN1, RED1, or BLUE1.","1","Base",""  ],
   ["Sneak Attack IV","100","Rogue Class","During your turn, discard a card to deal your choice of BLACKBLACK, GREENGREEN, REDRED, or BLUEBLUE.","1","Base",""  ],
   ["Stroke of Luck","100","Rogue Class","Deal damage from Deception cards anywhere on the damage track.","1","Base",""  ],
   ["Extra Attack","30","Martial Class","When you defeat an encounter matching your Class Type, gain SWORD ICON.","2","Base",""  ],
   ["Extra Attack II","60","Martial Class","When you defeat any encounter, gain SWORD ICON.","2","Base",""  ],
   ["Extra Attack III","100","Fighter Class","When you defeat any encounter, gain SWORD ICONSWORD ICON.","1","Base",""  ],
   ["Indomitable","100","Fighter Class","When you succeed at a Skill Check, draw the revealed card.","1","Base",""  ],
   ["Champion","20","Fighter Class","Equipment Pack: You must add one BLACK card and remove one card of any type.","1","Base",""  ],
   ["Improved Critical","10","Fighter Class & Champion","During your turn, if you clear two or more BLACK levels against the same encounter, deal +BLACK.","1","Base",""  ],
   ["Additional Style","30","Fighter Class & Champion","Continuous: Choose one additional Fighting Style.","1","Base",""  ],
   ["Remarkable Athlete","30","Fighter Class & Champion","When making a Martial Check, leave the revealed card on top of your draw deck instead of burying it.","1","Base",""  ],
   ["Superior Critical","50","Fighter Class & Champion","During your turn, if you clear two or more BLACK levels against the same encounter, deal one additional level of damage.","1","Base",""  ],
   ["Survivor","100","Fighter Class & Champion","If you have less than half your starting HP, you heal 1 HP at the start of your turn.","1","Base",""  ],
   ["Fighting Style Archery","10","Fighter Class or Ranger Class","Discard two Glory cards to Assist: BLACK. (Does not require a Feature slot.)","2","Base",""  ],
   ["Fighting Style Defense","10","Martial Class","During your turn, discard two Glory cards to have an encounter deal -1 damage. (Does not require a Feature slot.)","2","Base",""  ],
   ["Fighting Style Dueling","10","Martial Class","If you play Glory cards on two different encounters, deal BLACK to a third encounter. (Does not require a Feature slot.)","2","Base",""  ],
   ["Fighting Style Protection","10","Fighter Class or Paladin Class","During another player's turn, discard two Glory cards to have an encounter deal -1 damage. (Does not require a Feature slot.)","2","Base",""  ],
   ["Fighting Style Two-Weapon Fighting","15","Fighter Class or Ranger Class","If you play Glory cards on the same encounter, they deal 3 COLORLESS instead of the normal damage. (Does not require a Feature slot.)","2","Base",""  ],
   ["Fighting Style Great Weapon Fighting","15","Fighter Class or Paladin Class","Continuous: You can never play more than one Glory card during your turn, but it deals BLACKBLACK. (Does not require a Feature slot.)","2","Base",""  ],
   ["War Domain","10","Cleric Class","You also count as a MARTIAL Class. Equipment Pack: You must add one BLACK card; may remove one GREEN card.","1","Base",""  ],
   ["War Priest","20","Cleric Class & War Domain","When you play non-Basic BLACK and GREEN cards during your same turn, deal +BLACK or +GREEN damage.","1","Base",""  ],
   ["Guided Strike","30","Cleric Class & War Domain","During your turn, discard one Grace card to add +2 COLORLESS to any BLACK card you play.","1","Base",""  ],
   ["War God's Blessing","50","Cleric Class & War Domain","Once per Scene: Change up to 4 damage from a single source to any one color.","1","Base",""  ],
   ["Divine Strike","50","Cleric Class & War Domain","During your turn, your first non-Basic card to deal damage each turn deals +GREEN. (If a card deals damage to multiple targets, this only applies to one target.)","1","Base",""  ],
   ["Divine Strike II","100","Cleric Class & War Domain","Your first non-Basic card to deal damage each turn deals +GREEN. (If a card deals damage to multiple targets, this only applies to one target.)","1","Base",""  ],
   ["Second Wind","10","Fighter Class","Once per game, during a Short Rest: You heal 1 HP.","3","Base",""  ],
   ["Action Surge","15","Fighter Class","Short Rest: Draw one card and discard one card.","3","Base",""  ],
   ["Dramatic Flair","30","","If you play two cards during another player's turn, pay 1 gold to draw one card.","2","Base",""  ],
   ["Recovery","30","","When you defeat a non-token encounter that matches your primary Class Type, heal 1 HP.","2","Base",""  ],
   ["Tricks","30","","During your turn, discard the top card of your deck.","2","Base",""  ],
   ["Boon Companion","35","","When you play a second card during another player's turn, that card deals +1 COLORLESS damage.","1","Base",""  ],
   ["Well Prepared","35","","During your turn, pay 2 gold to draw one card.","1","Base",""  ],
   ["Fate's Hand","40","","Once per game: At the start of the Dragonfire phase, move the Dragonfire Deck one player to the left. (That new player is now the party leader.)","1","Base",""  ],
   ["Fury","40","","Once per turn: If you would heal, draw one card instead.","1","Base",""  ],
   ["Observant","40","","During your turn, discard two non-Basic cards of the same color to return another card of that color from your discard to your hand.","1","Base",""  ],
   ["Inspiring Leader","50","","Deal 1 COLORLESS during your turn. (You need not play any cards.)","1","Base",""  ],
   ["Mercenary","20","","When you defeat a non-token encounter that matches your primary Class Type, its gold value increases by 1.","2","Base",""  ],
   ["Penetrating Senses","20"," Elf","If your Keen Senses Skill Check is a Success, ignore the Surprise effect entirely.","2","Base",""  ],
   ["Riches","20","Dwarf","Continuous: Increase your starting gold by 1.","2","Base",""  ],
   ["Skilled","20","","When you defeat a non-token encounter that matches your primary Class Type, draw one card, then discard one card.","2","Base",""  ],
   ["Divine Hand","30","","When you play at least one card of each color in a turn, heal 1HP.","2","Base",""  ],
   ["Double Move","30","","Deal +1 COLORLESS damage with a card if you play another card with the same name that turn.","2","Base",""  ],
   ["Fair Share","15","","When another player defeats an encounter facing you, gain gold equal to the active player's share instead of your normal share.","2","Base",""  ],
   ["Honed","15","","When you play only one card during your turn, it deals +1 COLORLESS damage.","2","Base",""  ],
   ["Bulk Goods","20","","If you buy two cards that match your primary Class Type during a turn, pay 1 less gold for the second card.","2","Base",""  ],
   ["Constitution","20","Half-Orc","Continuous: Increase your starting HP by 1.","2","Base",""  ],
   ["Flexibility","20","Human or Half-Elf","Continuous: Increase your starting hand by 1.","2","Base",""  ],
   ["Keen Senses","20","Half-Elf","Make a Skill Check. Success: Shift Surprise effect one player to the left.","2","Base",""  ],
   ["Initiate","5","","Exchange 2 COLORLESS for BLUE.","2","Base",""  ],
   ["Mobile","5","","When you purchase a card that costs 8 or more, move a non-Location encounter.","2","Base",""  ],
   ["Scavenger","5","","When you purchase a card that costs 8 or more, return a Basic card from your discard to your hand.","2","Base",""  ],
   ["Tavern Brawler","5","","Exchange 2 COLORLESS for BLACK.","2","Base",""  ],
   ["Herbalism","5","","Once per game: Pay 3 gold to heal a character 1 HP.","2","Base",""  ],
   ["Merchant's Guild","5","","At the start of the game, add 1 Market Slot.","2","Base",""  ],
   ["Adherent","5","","Exchange 2 COLORLESS for GREEN.","2","Base",""  ],
   ["Caravan","5","","Once per game, during your turn: Cycle all cards in the Market.","2","Base",""  ],
   ["Cunning","5","","Exchange 2 COLORLESS for RED.","2","Base",""  ],
   ["Dextrous","5","","When you purchase a card that costs 8 or more, draw a card, then discard a card.","2","Base",""  ],
   ["Fundamentals","5","","At the start of the game, add one Basic card to your Equipment Pack.","2","Base",""  ],
   ["Haggling","5","","When you purchase a card that costs 6 or more, gain 1 gold.","2","Base",""  ],
   ["Acolyte","Background","","Once per game, during your turn: Exchange 2 COLORLESS for 1 GREEN.","2","Heroes of Sword Coast","1"  ],
   ["Criminal","Background","","Once per game, during your turn: Discard one card for 1 gold.","2","Heroes of Sword Coast","1"  ],
   ["Entertainer","Background","","Once per game, during your turn: Discard a card and you may permanently ignore a Requires X Play/Purchase/Class on one card.","2","Heroes of Sword Coast","1"  ],
   ["Folk Hero","Background","","Once per game, during your turn: Exchange 2 HP for 1 gold.","2","Heroes of Sword Coast","2"  ],
   ["Guild Artisan","Background","","Once per game, during your turn: Exchange 2 COLORLESS for 1 RED.","2","Heroes of Sword Coast","2"  ],
   ["Hermit","Background","","Once per game, during your turn: Exchange 1 gold to draw one card.","2","Heroes of Sword Coast","2"  ],
   ["Noble","Background","","Once per game, during your turn: Exchange 1 gold to for 1 HP.","2","Heroes of Sword Coast","3"  ],
   ["Outlander","Background","","Once per game, during your turn: Discard one card for 1 HP.","2","Heroes of Sword Coast","3"  ],
   ["Sage","Background","","Once per game, during your turn: Exchange 2 COLORLESS for 1 BLUE.","2","Heroes of Sword Coast","3"  ],
   ["Sailor","Background","","Once per game, during your turn: Exchange 2 HP to draw one card.","2","Heroes of Sword Coast","4"  ],
   ["Soldier","Background","","Once per game, during your turn: Exchange 2 COLORLESS for 1 BLACK.","2","Heroes of Sword Coast","4"  ],
   ["Street Urchin","Background","","Once per game, during your turn: Steal one gold from another player.","2","Heroes of Sword Coast","4"  ],
   ["Adherent","5","","Exchange 2 COLORLESS for GREEN.","2","Heroes of Sword Coast","5"  ],
   ["Caravan","5","","Once per game, during your turn: Cycle all cards in the Market.","2","Heroes of Sword Coast","5"  ],
   ["Cunning","5","","Exchange 2 COLORLESS for RED.","2","Heroes of Sword Coast","5"  ],
   ["Dextrous","5","","When you purchase a card that costs 8 or more, draw a card, then discard a card.","2","Heroes of Sword Coast","6"  ],
   ["Fundamentals","5","","At the start of the game, add one Basic card to your Equipment Pack.","2","Heroes of Sword Coast","6"  ],
   ["Haggling","5","","When you purchase a card that costs 6 or more, gain 1 gold.","2","Heroes of Sword Coast","6"  ],
   ["Initiate","5","","Exchange 2 COLORLESS for BLUE.","2","Heroes of Sword Coast","7"  ],
   ["Mobile","5","","When you purchase a card that costs 8 or more, move a non-Location encounter.","2","Heroes of Sword Coast","7"  ],
   ["Scavenger","5","","When you purchase a card that costs 8 or more, return a Basic card from your discard to your hand.","2","Heroes of Sword Coast","7"  ],
   ["Tavern Brawler","5","","Exchange 2 COLORLESS for BLACK.","2","Heroes of Sword Coast","8"  ],
   ["Herbalism","5","","Once per game: Pay 3 gold to heal a character 1 HP.","2","Heroes of Sword Coast","8"  ],
   ["Merchant's Guild","5","","At the start of the game, add 1 Market Slot.","2","Heroes of Sword Coast","8"  ],
   ["On the Sly","10","","When you purchase a card, pay 1 less gold and put the card into your discard instead of your hand.","2","Heroes of Sword Coast","9"  ],
   ["Tough","10","","Continuous: Increase your starting HP by 1.","2","Heroes of Sword Coast","9"  ],
   ["Training","10","","Continuous: Increase your starting hand by 1.","2","Heroes of Sword Coast","9"  ],
   ["Tranquility","10","","When you are forced to discard one or more cards, draw a card after discarding.","2","Heroes of Sword Coast","10"  ],
   ["Wealthy","10","","Continuous: Increase your starting gold by 1.","2","Heroes of Sword Coast","10"  ],
   ["Denial","15","","Each time you would heal, gain 1 gold instead.","2","Heroes of Sword Coast","10"  ],
   ["Fair Share","15","","When another player defeats an encounter facing you, gain gold equal to the active player's share instead of your normal share.","2","Heroes of Sword Coast","11"  ],
   ["Honed","15","","When you play only one card during your turn, it deals +1 COLORLESS damage.","2","Heroes of Sword Coast","11"  ],
   ["Bulk Goods","20","","If you buy two cards that match your primary Class Type during a turn, pay 1 less gold for the second card.","2","Heroes of Sword Coast","11"  ],
   ["Constitution","20","Half-Orc","Continuous: Increase your starting HP by 1.","2","Heroes of Sword Coast","12"  ],
   ["Flexibility","20","Human or Half-Elf","Continuous: Increase your starting hand by 1.","2","Heroes of Sword Coast","12"  ],
   ["Keen Senses","20","Half-Elf","Make a Skill Check. Success: Shift Surprise effect one player to the left.","2","Heroes of Sword Coast","12"  ],
   ["Mercenary","20","","When you defeat a non-token encounter that matches your primary Class Type, its gold value increases by 1.","2","Heroes of Sword Coast","13"  ],
   ["Penetrating Senses","20"," Elf","If your Keen Senses Skill Check is a Success, ignore the Surprise effect entirely.","2","Heroes of Sword Coast","13"  ],
   ["Riches","20","Dwarf","Continuous: Increase your starting gold by 1.","2","Heroes of Sword Coast","13"  ],
   ["Skilled","20","","When you defeat a non-token encounter that matches your primary Class Type, draw one card, then discard one card.","2","Heroes of Sword Coast","14"  ],
   ["Divine Hand","30","","When you play at least one card of each color in a turn, heal 1HP.","2","Heroes of Sword Coast","14"  ],
   ["Double Move","30","","Deal +1 COLORLESS damage with a card if you play another card with the same name that turn.","2","Heroes of Sword Coast","14"  ],
   ["Dramatic Flair","30","","If you play two cards during another player's turn, pay 1 gold to draw one card.","2","Heroes of Sword Coast","15"  ],
   ["Recovery","30","","When you defeat a non-token encounter that matches your primary Class Type, heal 1 HP.","2","Heroes of Sword Coast","15"  ],
   ["Tricks","30","","During your turn, discard the top card of your deck.","2","Heroes of Sword Coast","15"  ],
   ["Boon Companion","35","","When you play a second card during another player's turn, that card deals +1 COLORLESS damage.","1","Heroes of Sword Coast","16"  ],
   ["Well Prepared","35","","During your turn, pay 2 gold to draw one card.","1","Heroes of Sword Coast","16"  ],
   ["Fate's Hand","40","","Once per game: At the start of the Dragonfire phase, move the Dragonfire Deck one player to the left. (That new player is now the party leader.)","1","Heroes of Sword Coast","16"  ],
   ["Fury","40","","Once per turn: If you would heal, draw one card instead.","1","Heroes of Sword Coast","16"  ],
   ["Observant","40","","During your turn, discard two non-Basic cards of the same color to return another card of that color from your discard to your hand.","1","Heroes of Sword Coast","16"  ],
   ["Inspiring Leader","50","","Deal 1 COLORLESS during your turn. (You need not play any cards.)","1","Heroes of Sword Coast","16"  ],
   ["Turn Undead","20","Cleric or Paladin Class","Once per Scene: All Undead encounters must Save. Failure: Those encounters must skip their next attack.","3","Heroes of Sword Coast","17"  ],
   ["Destroy Undead","75","Cleric Class","Once per Scene: All Undead encounters must Save. Failure: Those encounters must skip their next attack and take 1 level of damage","1","Heroes of Sword Coast","17"  ],
   ["Destroy Undead II","100","Cleric Class","Once per Scene: All Undead encounters must Save. Failure: Those encounters must skip their next attack and take 2 levels of damage","1","Heroes of Sword Coast","17"  ],
   ["Divine Intervention","100","Cleric Class","Once per game, during your turn: Shuffle your discard into your draw deck. Choose a number of cards to draw. If any of them are not Devotion cards, discard all the cards drawn this way.","1","Heroes of Sword Coast","17"  ],
   ["Life Domain","10","Cleric Class","Equipment Pack: You must remove one BLACK card and add one GREEN card.","1","Heroes of Sword Coast","18"  ],
   ["Disciple of Life","25","Cleric Class & Life Domain","When you heal a character, return one Grace card from your discard to your hand.","1","Heroes of Sword Coast","18"  ],
   ["Preserve Life","30","Cleric Class & Life Domain","Once per Scene, during your turn: Discard one Grace card to heal any character 1 HP.","1","Heroes of Sword Coast","18"  ],
   ["Divine Strike","50","Cleric Class & War Domain","During your turn, your first non-Basic card to deal damage deals +1 GREEN. (If a card deals damage to multiple targets, this only applies to one target.)","1","Heroes of Sword Coast","18"  ],
   ["Preserve Life II","50","Cleric Class & Life Domain","Once per Scene, during your turn: Discard one Grace card to heal any character 1 HP and yourself 1 HP.","1","Heroes of Sword Coast","18"  ],
   ["Supreme Healing","100","Cleric Class & Life Domain","When healing any character, make a Devotion Check. Success: Heal +1 HP.","1","Heroes of Sword Coast","18"  ],
   ["War Domain","10","Cleric Class","You also count as a MARTIAL Class. Equipment Pack: You must add one BLACK card; may remove one GREEN card.","1","Heroes of Sword Coast","19"  ],
   ["War Priest","20","Cleric Class & War Domain","When you play non-Basic BLACK and GREEN cards during your same turn, deal +BLACK or +GREEN damage.","1","Heroes of Sword Coast","19"  ],
   ["Guided Strike","30","Cleric Class & War Domain","During your turn, discard one Grace card to add +2 COLORLESS to any BLACK card you play.","1","Heroes of Sword Coast","19"  ],
   ["War God's Blessing","50","Cleric Class & War Domain","Once per Scene: Change up to 4 damage from a single source to any one color.","1","Heroes of Sword Coast","19"  ],
   ["Divine Strike","50","Cleric Class & War Domain","During your turn, your first non-Basic card to deal damage each turn deals +GREEN. (If a card deals damage to multiple targets, this only applies to one target.)","1","Heroes of Sword Coast","19"  ],
   ["Divine Strike II","100","Cleric Class & War Domain","Your first non-Basic card to deal damage each turn deals +GREEN. (If a card deals damage to multiple targets, this only applies to one target.)","1","Heroes of Sword Coast","19"  ],
   ["Second Wind","10","Fighter Class","Once per game, during a Short Rest: You heal 1 HP.","3","Heroes of Sword Coast","20"  ],
   ["Action Surge","15","Fighter Class","Short Rest: Draw one card and discard one card.","3","Heroes of Sword Coast","20"  ],
   ["Fighting Style Archery","10","Fighter Class or Ranger Class","Discard two Glory cards to Assist: BLACK. (Does not require a Feature slot.)","2","Heroes of Sword Coast","21"  ],
   ["Fighting Style Defense","10","Martial Class","During your turn, discard two Glory cards to have an encounter deal -1 damage. (Does not require a Feature slot.)","2","Heroes of Sword Coast","21"  ],
   ["Fighting Style Dueling","10","Martial Class","If you play Glory cards on two different encounters, deal BLACK to a third encounter. (Does not require a Feature slot.)","2","Heroes of Sword Coast","21"  ],
   ["Fighting Style Protection","10","Fighter Class or Paladin Class","During another player's turn, discard two Glory cards to have an encounter deal -1 damage. (Does not require a Feature slot.)","2","Heroes of Sword Coast","22"  ],
   ["Fighting Style Two-Weapon Fighting","15","Fighter Class or Ranger Class","If you play Glory cards on the same encounter, they deal 3 COLORLESS instead of the normal damage. (Does not require a Feature slot.)","2","Heroes of Sword Coast","22"  ],
   ["Fighting Style Great Weapon Fighting","15","Fighter Class or Paladin Class","Continuous: You can never play more than one Glory card during your turn, but it deals BLACKBLACK. (Does not require a Feature slot.)","2","Heroes of Sword Coast","22"  ],
   ["Extra Attack","30","Martial Class","When you defeat an encounter matching your Class Type, gain SWORD ICON.","2","Heroes of Sword Coast","23"  ],
   ["Extra Attack II","60","Martial Class","When you defeat any encounter, gain SWORD ICON.","2","Heroes of Sword Coast","23"  ],
   ["Extra Attack III","100","Fighter Class","When you defeat any encounter, gain SWORD ICONSWORD ICON.","1","Heroes of Sword Coast","23"  ],
   ["Indomitable","100","Fighter Class","When you succeed at a Skill Check, draw the revealed card.","1","Heroes of Sword Coast","23"  ],
   ["Champion","20","Fighter Class","Equipment Pack: You must add one BLACK card and remove one card of any type.","1","Heroes of Sword Coast","24"  ],
   ["Improved Critical","10","Fighter Class & Champion","During your turn, if you clear two or more BLACK levels against the same encounter, deal +BLACK.","1","Heroes of Sword Coast","24"  ],
   ["Additional Style","30","Fighter Class & Champion","Continuous: Choose one additional Fighting Style.","1","Heroes of Sword Coast","24"  ],
   ["Remarkable Athlete","30","Fighter Class & Champion","When making a Martial Check, leave the revealed card on top of your draw deck instead of burying it.","1","Heroes of Sword Coast","24"  ],
   ["Superior Critical","50","Fighter Class & Champion","During your turn, if you clear two or more BLACK levels against the same encounter, deal one additional level of damage.","1","Heroes of Sword Coast","24"  ],
   ["Survivor","100","Fighter Class & Champion","If you have less than half your starting HP, you heal 1 HP at the start of your turn.","1","Heroes of Sword Coast","24"  ],
   ["Eldritch Knight","20","Fighter Class","You also count as ARCANE Class. Equipment Pack: You must add one BLUE card and remove one BLACK card.","1","Heroes of Sword Coast","25"  ],
   ["Weapon Bond","20","Fighter Class & Eldritch Knight","During your turn, discard any one BLUE card to draw one card.","1","Heroes of Sword Coast","25"  ],
   ["War Magic","40","Fighter Class & Eldritch Knight","Every time you play a Cantrip card, deal +1 BLACK.","1","Heroes of Sword Coast","25"  ],
   ["Arcane Charge","50","Fighter Class & Eldritch Knight","Once per Scene, during your turn: Move all encounters facing one player to face you. If you discard any one BLUE card, each encounter deals -1 damage.","1","Heroes of Sword Coast","25"  ],
   ["Eldritch Strike","50","Fighter Class & Eldritch Knight","If you deal damage from two BLACK cards and one BLUE card against the same encounter, deal +BLUE, BLUE to the same encounter","1","Heroes of Sword Coast","25"  ],
   ["Improved War Magic","100","Fighter Class & Eldritch Knight","All BLUE cards gain SWORD ICON.","1","Heroes of Sword Coast","25"  ],
   ["Expertise","15","Deception Class","Before the game starts, purchase any RED card costing 2 or less.","2","Heroes of Sword Coast","26"  ],
   ["Expertise II","30","Deception Class","Before the game starts, purchase a RED card costing 2 or less and replace a Stealth card with it.","2","Heroes of Sword Coast","26"  ],
   ["Expertise III","60","Deception Class","Before the game starts, purchase any two RED cards, each costing 2 or less, and replace up to two Stealth cards with them.","1","Heroes of Sword Coast","26"  ],
   ["Expertise IV","100","Deception Class","Before the game starts, purchase up to three RED cards, each costing 2 or less, and replace up to three Stealth cards with them.","1","Heroes of Sword Coast","26"  ],
   ["Thieves' Cant","10","Rogue Class","During your turn, any other player with Thieves' Cant may play one card as if it had Assist.","2","Heroes of Sword Coast","27"  ],
   ["Evasion","20","Rogue Class","During your turn, discard one card to have one encounter facing you deal -1 damage.","1","Heroes of Sword Coast","27"  ],
   ["Evasion II","50","Rogue Class","During your turn, discard two cards to have all encounters facing you deal -1 damage.","1","Heroes of Sword Coast","27"  ],
   ["Evasion III","100","Rogue Class","During your turn, discard two cards to have all encounters facing you deal -1 damage.","1","Heroes of Sword Coast","27"  ],
   ["Reliable Talent","50","Rogue Class","When you succeed on a Deception Check, pay 1 gold to draw the revealed card.","1","Heroes of Sword Coast","27"  ],
   ["Sneak Attack","10","Rogue Class","During your turn, discard a card to deal RED.","2","Heroes of Sword Coast","28"  ],
   ["Sneak Attack II","30","Rogue Class","During your turn, discard a card to deal your choice of BLACK, GREEN, RED, or BLUE.","1","Heroes of Sword Coast","28"  ],
   ["Sneak Attack III","60","Rogue Class","During your turn, discard a card to deal your choice of BLACK1, GREEN1, RED1, or BLUE1.","1","Heroes of Sword Coast","28"  ],
   ["Sneak Attack IV","100","Rogue Class","During your turn, discard a card to deal your choice of BLACKBLACK, GREENGREEN, REDRED, or BLUEBLUE.","1","Heroes of Sword Coast","28"  ],
   ["Stroke of Luck","100","Rogue Class","Deal damage from Deception cards anywhere on the damage track.","1","Heroes of Sword Coast","28"  ],
   ["Arcane Trickster","20","Rogue Class","You also count as ARCANE Class. Equipment Pack: You must add one BLUE card and remove one RED card.","2","Heroes of Sword Coast","29"  ],
   ["Ledgermain","20","Rogue Class & Arcane Trickster","Play BLUE and RED cards against Locations as Assists.","1","Heroes of Sword Coast","29"  ],
   ["Magical Ambush","40","Rogue Class & Arcane Trickster","During your turn, when dealing RED damage to an encounter not facing you, deal it +BLUE.","1","Heroes of Sword Coast","29"  ],
   ["Versatile Trickster","50","Rogue Class & Arcane Trickster","During your turn, if you play BLUE and RED cards, return a Basic card to your hand from your discard.","1","Heroes of Sword Coast","29"  ],
   ["Spell Thief","100","Rogue Class & Arcane Trickster","Once per Scene: Choose a BLUE encounter. This encounter must skip its next attack. The player deals its damage as colorless against another encounter.","1","Heroes of Sword Coast","29"  ],
   ["Arcane Trickster","20","Rogue Class","You also count as ARCANE Class. Equipment Pack: You must add one BLUE card and remove one RED card.","2","Heroes of Sword Coast","29"  ],
   ["Ledgermain","20","Rogue Class & Arcane Trickster","Play BLUE and RED cards against Locations as Assists.","1","Heroes of Sword Coast","29"  ],
   ["Magical Ambush","40","Rogue Class & Arcane Trickster","During your turn, when dealing RED damage to an encounter not facing you, deal it +BLUE.","1","Heroes of Sword Coast","29"  ],
   ["Versatile Trickster","50","Rogue Class & Arcane Trickster","During your turn, if you play BLUE and RED cards, return a Basic card to your hand from your discard.","1","Heroes of Sword Coast","29"  ],
   ["Spell Thief","100","Rogue Class & Arcane Trickster","Once per Scene: Choose a BLUE encounter. This encounter must skip its next attack. The player deals its damage as colorless against another encounter.","1","Heroes of Sword Coast","29"  ],
   ["Thief","20","Rogue Class","Increase your starting gold by 1. Equipment Pack: You must add one RED card and remove one card of any type.","1","Heroes of Sword Coast","30"  ],
   ["Second-Storey Work","20","Rogue Class & Thief","During your turn, you may move normally or move after your Deal Damage phase.","1","Heroes of Sword Coast","30"  ],
   ["Supreme Sneak","30","Rogue Class & Thief","If you play no cards during your turn, you may return any Basic card from your discard to your hand.","1","Heroes of Sword Coast","30"  ],
   ["Fast Hands","40","Rogue Class & Thief","During your turn, make a Deception Check. Success: You may leave the card on top of your deck","1","Heroes of Sword Coast","30"  ],
   ["Use Magic Device","50","Rogue Class & Thief","At the start of the game: You ignore all Class restrictions on Magic Items. Your Magic Items deal +1 COLORLESS.","1","Heroes of Sword Coast","30"  ],
   ["Thief's Reflexes","100","Rogue Class & Thief","When a non-token encounter is placed facing you (including during the Encounter phase), immediately return a card from your discard into your hand and you may immediately play this card on that encounter.","1","Heroes of Sword Coast","30"  ],
   ["Arcane Recovery","15","Arcane Class","During a Short Rest: Draw one card and discard one card.","2","Heroes of Sword Coast","31"  ],
   ["Arcane Recovery II","30","Arcane Class","During a Short Rest: Draw up to two cards. Then discard that number of cards.","2","Heroes of Sword Coast","31"  ],
   ["Arcane Recovery III","60","Arcane Class","During a Short Rest: Draw up to two cards. Then discard one card.","1","Heroes of Sword Coast","31"  ],
   ["Arcane Recovery IV","100","Arcane Class","During a Short Rest: Draw up to three cards. For each card drawn you must pay HP or discard one card.","1","Heroes of Sword Coast","31"  ],
   ["Magical Adept","10","Arcane Class","During your turn, discard one BLUE card to buy one BLUE card costing 5 or less from the Market and play it immediately.","2","Heroes of Sword Coast","32"  ],
   ["Warcaster","20","Arcane Class","Continuous: You may use any Armor. You may use any Shield except Deception; your Shield Magic Item Limitations is 1. Equipment Pack: You must remove one BLUE card and add one BLACK card.","2","Heroes of Sword Coast","32"  ],
   ["Spell Sniper","40","Arcane Class","Deal damage from Cantrip cards anywhere on the damage Track.","2","Heroes of Sword Coast","32"  ],
   ["Conjuration (Savant)","25","Wizard Class","All Conjuration cards cost -1. Equipment Pack: You must add one BLUE card and remove one card of any type.","2","Heroes of Sword Coast","33"  ],
   ["Minor Conjuration","10","Wizard Class & Conjuration (Savant)","Once per turn: Exchange 2 COLORLESS for BLACK or RED.","1","Heroes of Sword Coast","33"  ],
   ["Benign Transposition","30","Wizard Class & Conjuration (Savant)","Once per Scene, during your turn: Swap all encounters and Locations facing you with those of an adjacent player.","1","Heroes of Sword Coast","33"  ],
   ["Focused Conjuration","50","Wizard Class & Conjuration (Savant)","Once per Scene: After you play a Conjuration card, place it on top of your draw deck instead of in your discard.","1","Heroes of Sword Coast","33"  ],
   ["Focused Conjuration II","100","Wizard Class & Conjuration (Savant)","Once per Scene: After you play a Conjuration card, place it in your hand instead of in your discard.","1","Heroes of Sword Coast","33"  ],
   ["Evocation (Savant)","25","Wizard Class","All Evocation cards cost -1. Equipment Pack: You must add one BLUE card and remove one card of any type.","2","Heroes of Sword Coast","34"  ],
   ["Sculpt Spells","10","Wizard Class & Evocation (Savant)","Whenever an Evocation card deals damage to multiple encounters, it can also deal that multiple element to one additional encounter.","1","Heroes of Sword Coast","34"  ],
   ["Potent Cantrip","30","Wizard Class & Evocation (Savant)","If you play two Cantrips on the same encounter, deal + BLUE to the same encounter.","1","Heroes of Sword Coast","34"  ],
   ["Empower Evocation","50","Wizard Class & Evocation (Savant)","During your turn, discard any card to add twice its cost in colorless damage to any Evocation card's damage.","1","Heroes of Sword Coast","34"  ],
   ["Overchannel","100","Wizard Class & Evocation (Savant)","During your turn, add +2 COLORLESS to all non-Basic BLUE cards.","1","Heroes of Sword Coast","34"  ],
   ["Wild Shape","25","Druid Class","Once per Scene: If you play no cards during your turn, deal [G][1] and you take no damage.","3","Heroes of Sword Coast","35"  ],
   ["Wild Shape II","50","Druid Class","Once per Scene: If you play no cards during your turn, deal [G][G][1] and you take no damage.","2","Heroes of Sword Coast","35"  ],
   ["Wild Shape III","100","Druid Class","Once per Scene: If you play no cards during your turn, deal [G][G][G] and you take no damage. Additionally, move one encounter to face you.","1","Heroes of Sword Coast","35"  ],
   ["Druidic","10","Druid Class","During your turn, any other player with Druidic may play one card as if it had Assist.","1","Heroes of Sword Coast","36"  ],
   ["Circle of the Land","10","Druid Class","Permanently choose a Class Type to be your Chosen Type: ____. Equipment Pack: You must remove one GREEN card and add one Basic card of the Chosen Type.","1","Heroes of Sword Coast","36"  ],
   ["Bonus Grace","10","Druid Class & Circle of the Land","If you played no GREEN cards on your turn, deal [G].","1","Heroes of Sword Coast","36"  ],
   ["Natural Recovery","10","Druid Class & Circle of the Land","During a Short Rest: Shuffle one card from your discard into your deck.","1","Heroes of Sword Coast","36"  ],
   ["Nature's Sanctuary","30","Druid Class & Circle of the Land","When a card you played deals damage to an encounter whose color matches the Chosen Type, it must Save. Failure: That encounter must skip its next attack.","1","Heroes of Sword Coast","36"  ],
   ["Nature's Sanctuary II","100","Druid Class & Circle of the Land","When a card you played deals damage to an encounter whose color matches the Chosen Type, it must Save. Failure: That encounter must skip its next attack. Every card dealing damage to it this turn deals +1 COLORLESS.","1","Heroes of Sword Coast","36"  ],
   ["Druidic","10","Druid Class","During your turn, any other player with Druidic may play one card as if it had Assist.","1","Heroes of Sword Coast","37"  ],
   ["Circle of the Moon","20","Druid Class","Increase your starting HP by 1. Equipment Pack: You must remove one GREEN card and add either one BLACK or one RED card.","1","Heroes of Sword Coast","37"  ],
   ["Combat Shape","15","Druid Class & Circle of the Moon","When you activate Wild Shape, discard two cards to heal 1 HP.","1","Heroes of Sword Coast","37"  ],
   ["Primal Strike","30","Druid Class & Circle of the Moon","Wild Shape deals +2 COLORLESS.","1","Heroes of Sword Coast","37"  ],
   ["Elemental Shape","50","Druid Class & Circle of the Moon","Wild Shape deals +1 COLORLESS. Additionally, exchange all of Wild Shape's [G] for [G], [A], [M], or [R].","1","Heroes of Sword Coast","37"  ],
   ["Thousand Forms","100","Druid Class & Circle of the Moon","Activate Wild Shape twice per Scene.","1","Heroes of Sword Coast","37"  ],
   ["Favored Enemy","10","Ranger Class","Permanently choose a non-Humanoid Encounter Type to be your Chosen Enemy: ____. During your turn, the first BLACK damage dealt to your Chosen Enemy deals +1 COLORLESS.","2","Heroes of Sword Coast","38"  ],
   ["Explorer","15","Ranger Class","Permanently choose an Encounter Environment that is not Dungeon or City: ___. Once per Scene: During your turn, if current game includes that Environment, you may pay 1 gold to draw one card.","2","Heroes of Sword Coast","38"  ],
   ["Primeval Awareness","20","Ranger Class","At the end of the Encounter phase, swap each Chosen Enemy encounter in play with another encounter facing you.","2","Heroes of Sword Coast","38"  ],
   ["Veteran","25","Ranger Class","Continuous: Favored Enemy & Explorer Features do not require Feature slots.","2","Heroes of Sword Coast","39"  ],
   ["Hide in Plain Sight","40","Ranger Class","Choose one encounter attacking you during the first round of a Scene. It must Save. Failure: That encounter must skip its next attack.","2","Heroes of Sword Coast","39"  ],
   ["Feral Senses","100","Ranger Class","Continuous: Increase your starting cards, starting gold and starting HP by 2. Permanently lose Feature Slot 6.","1","Heroes of Sword Coast","39"  ],
   ["Superior Hunter","100","Ranger Class & Hunter","During your turn, choose an encounter facing you and deal its damage as colorless against another encounter.","1","Heroes of Sword Coast","39"  ],
   ["Hunter","15","Ranger Class","Increase your starting hand by 1 and decrease your starting gold by 1. Equipment Pack: You must add one BLACK card and remove one card of any type.","1","Heroes of Sword Coast","40"  ],
   ["Hunter's Prey","20","Ranger Class & Hunter","During your turn, if you play Hunter's Mark, return a Glory card from your discard to your hand.","2","Heroes of Sword Coast","40"  ],
   ["Defensive Tactics","30","Ranger Class & Hunter","You may ignore Surprise effects.","2","Heroes of Sword Coast","40"  ],
   ["Multiattack","50","Ranger Class & Hunter","Once per Scene: An Assist you play deals non-level damage to all encounters facing another player.","1","Heroes of Sword Coast","40"  ],
   ["Multiattack","50","Ranger Class & Hunter","Once per Scene: An Assist you play deals non-level damage to all encounters facing another player.","1","Heroes of Sword Coast","41"  ],
   ["Beastmaster","20","Ranger Class","Increase your starting HP by 2 and decrease your starting gold by 1. Equipment Pack: You must add one GREEN card and remove one card of any type.","1","Heroes of Sword Coast","41"  ],
   ["Ranger's Companion","35","Ranger Class & Beastmaster","During your turn, reveal the top card of your deck. If it is a Basic card, play it; otherwise discard it.","1","Heroes of Sword Coast","41"  ],
   ["Ranger's Companion II","50","Ranger Class & Beastmaster","During your turn, reveal the top card of your deck. If it is a Basic card, play it; otherwise you may discard it or bury it.","1","Heroes of Sword Coast","41"  ],
   ["Bestial Fury","25","Ranger Class & Beastmaster","Activate Ranger's Companion twice per turn.","1","Heroes of Sword Coast","41"  ],
   ["Bestial Fury II","50","Ranger Class & Beastmaster","Activate Ranger's Companion twice per turn.","1","Heroes of Sword Coast","41"  ],
   ["Bardic Inspiration","10","Bard Class","Discard a Performance card to let another player attempt a Skill Check again.","2","Heroes of Sword Coast","42"  ],
   ["Bardic Inspiration II","50","Bard Class","Discard a Performance card to let another player attempt a Skill Check again or to deal +2 COLORLESS damage.","2","Heroes of Sword Coast","42"  ],
   ["Bardic Inspiration III","100","Bard Class","Discard a Performance card to let another player attempt a Skill Check again, to deal +2 COLORLESS damage, or to draw a card.","2","Heroes of Sword Coast","42"  ],
   ["Font of Inspiration","50","Bard Class","Continuous: Equipment Pack: You must add one Performance card and remove one card of any type.","3","Heroes of Sword Coast","43"  ],
   ["Magical Secrets","50","Bard Class","Once per Scene: Discard a card to play one BLUE or GREEN card from another player's discard costing 4 or less, ignoring any Play/Purchase Requirements. (Return to that player's discard.)","3","Heroes of Sword Coast","43"  ],
   ["Jack of All Trades","15","Bard Class","During play, Performance cards count as Deception.","2","Heroes of Sword Coast","44"  ],
   ["Song of Rest","30","Bard Class","At the end of a Short Rest: Heal any character 1 HP.","2","Heroes of Sword Coast","44"  ],
   ["Song of Rest II","60","Bard Class","At the end of a Short Rest: Heal up to 2 HP, distributed as you choose.","1","Heroes of Sword Coast","44"  ],
   ["Song of Rest III","100","Bard Class","At the end of a Short Rest: Heal up to 3 HP, distributed as you choose.","1","Heroes of Sword Coast","44"  ],
   ["College of Lore","20","Bard Class","Increase your starting hand by 1. Equipment Pack: You must add one Basic BLUE, GREEN, RED, or BLACK card.","2","Heroes of Sword Coast","45"  ],
   ["Proficiencies","20","Bard Class & College of Lore","Before the game starts, you may buy any Market card costing 2 or less and replace a Basic card of the same color with it.","1","Heroes of Sword Coast","45"  ],
   ["Cutting Words","30","Bard Class & College of Lore","After an encounter Saves, discard a card to make it Save a second time. Additionally, that encounter deals -1 damage.","1","Heroes of Sword Coast","45"  ],
   ["Additional Magical Secrets","60","Bard Class & College of Lore","Continuous: Buy and play BLUE Market and Magic Item cards as if you are BLUE Class. All BLUE cards cost -1.","1","Heroes of Sword Coast","45"  ],
   ["Peerless Skill","100","Bard Class & College of Lore","If Performance is played with another card, duplicate that card's damage. (Does not duplicate text effects.)","1","Heroes of Sword Coast","45"  ],
   ["College of Valor","20","Bard Class","You also count as BLACK Class. Equipment Pack: You must add one BLACK card and remove one card of any type.","2","Heroes of Sword Coast","46"  ],
   ["Martial Proficiencies","20","Bard Class & College of Valor","Before the game starts, purchase one BLACK card costing 3 or less and add it to your Equipment Pack.","2","Heroes of Sword Coast","46"  ],
   ["Combat Inspiration","30","Bard Class & College of Valor","Bardic Inspiration deals +1 COLORLESS.","1","Heroes of Sword Coast","46"  ],
   ["Battle Magic","100","Bard Class & College of Valor","All Performance cards gain SWORD ICONSWORD ICON.","1","Heroes of Sword Coast","46"  ],
   ["Eldritch Invocations","20","Warlock Class","Continuous: Two Invocations do not require Feature slots.","2","Heroes of Sword Coast","47"  ],
   ["Eldritch Invocations II","30","Warlock Class","Continuous: Three Invocations do not require Feature slots.","2","Heroes of Sword Coast","47"  ],
   ["Eldritch Invocations III","40","Warlock Class","Continuous: Four Invocations do not require Feature slots.","2","Heroes of Sword Coast","47"  ],
   ["Invocation Agonizing Blast","15","Warlock Class","Your first Cantrip played during each Scene deals +1 COLORLESS.","2","Heroes of Sword Coast","48"  ],
   ["Invocation Book of Secrets","15","Warlock Class & Pact of the Tome","Once per Scene: Purchase one BLUE card from the Market discard.","2","Heroes of Sword Coast","48"  ],
   ["Invocation Eldritch Spear","15","Warlock Class","Once per Scene: Use a Cantrip card as an Assist.","2","Heroes of Sword Coast","48"  ],
   ["Invocation Eyes of the Rune Keeper","15","Warlock Class","Look at the next Dragonfire card.","2","Heroes of Sword Coast","49"  ],
   ["Invocation Repelling Blast","15","Warlock Class","Once per Scene: If you use only a single Cantrip card to clear a level on an encounter facing you, that encounter deals -1 damage.","2","Heroes of Sword Coast","49"  ],
   ["Invocation Voice of the Master","15","Warlock Class & Pact of the Chain","Once per Scene: Pact of the Chain II also lets you use text effects.","2","Heroes of Sword Coast","49"  ],
   ["Pact of the Blade","25","Warlock Class","During your turn, search your deck for a Glory card and put it in your hand.","1","Heroes of Sword Coast","50"  ],
   ["Pact of the Blade II","100","Warlock Class","During your turn, search your deck for an Uncommon or Rare Magical Weapon and put it in your hand.","1","Heroes of Sword Coast","50"  ],
   ["Pact of the Tome","30","Warlock Class","If you didn't play or discard a Cantrip card this turn, deal BLUE.","1","Heroes of Sword Coast","50"  ],
   ["Pact of the Tome II","100","Warlock Class","If you didn't play or discard a Cantrip card this turn, deal BLUE for every Cantrip in your hand.","1","Heroes of Sword Coast","50"  ],
   ["Pact of the Chain","35","Warlock Class","During your turn, reveal the top card of your deck. If it is a Basic card, play it; otherwise, discard it.","1","Heroes of Sword Coast","50"  ],
   ["Pact of the Chain II","100","Warlock Class","During your turn, reveal the top two cards of your deck. You must play them this turn but only to deal damage, ignoring text effects.","1","Heroes of Sword Coast","50"  ],
   ["Patron (Fey)","10","Warlock Class","Equipment Pack: you must add one BLUE card and remove one card of any type.","2","Heroes of Sword Coast","51"  ],
   ["Fey Presence","10","Warlock Class & Patron (Fey)","Once per Scene: Assign 1 point of damage dealt to you to an adjacent character.","1","Heroes of Sword Coast","51"  ],
   ["Misty Escape","40","Warlock Class & Patron (Fey)","Once per Scene: During your turn, choose an encounter facing you. It must Save. Failure: Move that encounter to face any character whose Class color matches that card.","1","Heroes of Sword Coast","51"  ],
   ["Beguiling Defenses","60","Warlock Class & Patron (Fey)","Once per Scene: During your turn, choose an encounter facing you. It must Save. Failure: That encounter deals no damage. Deal 1 level of damage to that encounter.","1","Heroes of Sword Coast","51"  ],
   ["Dark Delerium","100","Warlock Class & Patron (Fey)","Once per Scene: During your turn, choose an encounter facing you. It must Save every turn until it succeeds. Failure: That encounter must skip its next attack.","1","Heroes of Sword Coast","51"  ],
   ["Patron (Fiend)","10","Warlock Class","Equipment Pack: you must add one RED card and remove one card of any type.","2","Heroes of Sword Coast","52"  ],
   ["Dark One's Blessing","30","Warlock Class & Patron (Fiend)","If you defeat one or more encounters, gain 1 HP until the end of your turn.","1","Heroes of Sword Coast","52"  ],
   ["Dark One's Own Luck","40","Warlock Class & Patron (Fiend)","When making a Skill Check, you may reveal a card from the bottom of your deck. (Place that card on top of the deck instead of burying it.)","1","Heroes of Sword Coast","52"  ],
   ["Fiendish Resilience","60","Warlock Class & Patron (Fiend)","All BLACK encounters deal -1 damage to you.","1","Heroes of Sword Coast","52"  ],
   ["Hurl Through Hell","100","Warlock Class & Patron (Fiend)","Once per game: Choose an encounter. Play the top three cards from the Market discard on it, ignoring all requirements.","1","Heroes of Sword Coast","52"  ]])

;; Data
(def feature-map (distinct (map #(dissoc (zipmap titles %) :sticker) features)))

(def slot-list [:slot0 :slot1 :slot2 :slot3 :slot4 :slot5 :slot6 :weapon1 :weapon2
                :invocation1 :invocation2 :invocation3 :invocation4])

(def archetypes {"Fighter" "Martial"
                 "Paladin" "Martial"
                 "Cleric" "Devotion"
                 "Druid" "Devotion"
                 "Wizard" "Arcane"
                 "Warlock" "Arcane"
                 "Bard" "Deception"
                 "Rogue" "Deception"
                 "Ranger" "Martial"})

(def classes (keys archetypes))

(def races
  (sort ["Shield Dwarf" "Lightfoot Halfling" "Tiefling" "Moon Elf" "Wood Elf" "Rock Gnome" "Half-Orc"
         "Gold Dwarf" "Tiefling" "Sun Elf" "Human" "Forest Gnome" "Wood Elf" "Half-Elf"]))

(def paths {"Fighter" ["Non-specialised" "Champion" "Eldritch Knight"]
            "Rogue" ["Non-specialised" "Arcane Trickster" "Thief"]
            "Wizard" ["Non-specialised" "Conjuration (Savant)" "Evocation (Savant)"]
            "Cleric" ["Non-specialised" "Life Domain" "War Domain"]
            "Druid" ["Non-specialised" "Circle of the Land" "Circle of the Moon"]
            "Ranger" ["Non-specialised" "Hunter" "Beastmaster"]
            "Bard" ["Non-specialised" "College of Lore" "College of Valor"]
            "Warlock" ["Non-specialised" "Patron (Fey)" "Patron (Fiend)"]})